## Raw bindings to the tree-sitter C API.
##
## Types and procs are imported from the real `tree_sitter/api.h`, so struct
## layout is whatever the vendored runtime says it is rather than something we
## restated by hand. Verified against tree-sitter v0.26.12.
##
## Only the subset needed for one-shot parsing + queries is bound. Incremental
## editing (`ts_tree_edit`, `TSInput`) is deliberately absent: this library
## highlights static text.

import std/os

const
  tsVendorDir* {.strdefine.} = currentSourcePath().parentDir.parentDir.parentDir /
    "vendor" / "tree-sitter"
    ## Override with `-d:tsVendorDir=/path/to/tree-sitter` to build against a
    ## checkout elsewhere. Must be a tree-sitter source tree (has lib/src).

when not fileExists(tsVendorDir / "lib" / "src" / "lib.c"):
  {.error: "tree-sitter runtime not found under '" & tsVendorDir &
    "'. Run scripts/vendor.sh, or pass -d:tsVendorDir=<path>.".}

{.passC: "-I" & quoteShell(tsVendorDir / "lib" / "src").}
{.passC: "-I" & quoteShell(tsVendorDir / "lib" / "include").}
{.compile: tsVendorDir / "lib" / "src" / "lib.c".}

const hdr = "tree_sitter/api.h"

# ABI range this runtime accepts. A parser generated by a much newer or much
# older tree-sitter CLI must be rejected, not called -- calling one crashes.
const
  languageVersion* = 15       ## TREE_SITTER_LANGUAGE_VERSION
  minCompatibleVersion* = 13  ## TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION

type
  TSLanguage* {.importc, header: hdr, incompleteStruct.} = object
  TSParser* {.importc, header: hdr, incompleteStruct.} = object
  TSTree* {.importc, header: hdr, incompleteStruct.} = object
  TSQuery* {.importc, header: hdr, incompleteStruct.} = object
  TSQueryCursor* {.importc, header: hdr, incompleteStruct.} = object

  TSSymbol* = uint16

  TSPoint* {.importc, header: hdr, bycopy.} = object
    row*, column*: uint32

  TSNode* {.importc, header: hdr, bycopy.} = object
    context*: array[4, uint32]
    id*: pointer
    tree*: ptr TSTree

  TSQueryCapture* {.importc, header: hdr, bycopy.} = object
    node*: TSNode
    index*: uint32

  TSQueryMatch* {.importc, header: hdr, bycopy.} = object
    id*: uint32
    pattern_index*: uint16
    capture_count*: uint16
    captures*: ptr UncheckedArray[TSQueryCapture]

  TSQueryPredicateStep* {.importc, header: hdr, bycopy.} = object
    `type`*: TSQueryPredicateStepType
    value_id*: uint32

  # C enums are int-sized; without the size pragma Nim would pass one byte.
  TSQueryPredicateStepType* {.size: sizeof(cint).} = enum
    stepDone = 0, stepCapture = 1, stepString = 2

  TSQueryError* {.size: sizeof(cint).} = enum
    qeNone = 0, qeSyntax, qeNodeType, qeField, qeCapture, qeStructure, qeLanguage

{.push importc, header: hdr, cdecl.}

# --- language -----------------------------------------------------------
proc ts_language_abi_version*(self: ptr TSLanguage): uint32

# --- parser -------------------------------------------------------------
proc ts_parser_new*(): ptr TSParser
proc ts_parser_delete*(self: ptr TSParser)
proc ts_parser_set_language*(self: ptr TSParser, language: ptr TSLanguage): bool
proc ts_parser_parse_string*(self: ptr TSParser, old_tree: ptr TSTree,
                             str: cstring, length: uint32): ptr TSTree

# --- tree / node --------------------------------------------------------
proc ts_tree_delete*(self: ptr TSTree)
proc ts_tree_root_node*(self: ptr TSTree): TSNode
proc ts_node_type*(self: TSNode): cstring
proc ts_node_symbol*(self: TSNode): TSSymbol
proc ts_node_start_byte*(self: TSNode): uint32
proc ts_node_end_byte*(self: TSNode): uint32
proc ts_node_start_point*(self: TSNode): TSPoint
proc ts_node_end_point*(self: TSNode): TSPoint
proc ts_node_is_null*(self: TSNode): bool
proc ts_node_is_named*(self: TSNode): bool
proc ts_node_is_missing*(self: TSNode): bool
proc ts_node_is_error*(self: TSNode): bool
proc ts_node_has_error*(self: TSNode): bool
proc ts_node_parent*(self: TSNode): TSNode
proc ts_node_child_count*(self: TSNode): uint32
proc ts_node_child*(self: TSNode, child_index: uint32): TSNode
proc ts_node_descendant_count*(self: TSNode): uint32
proc ts_node_string*(self: TSNode): cstring  # caller frees

# --- query --------------------------------------------------------------
proc ts_query_new*(language: ptr TSLanguage, source: cstring, source_len: uint32,
                   error_offset: ptr uint32,
                   error_type: ptr TSQueryError): ptr TSQuery
proc ts_query_delete*(self: ptr TSQuery)
proc ts_query_pattern_count*(self: ptr TSQuery): uint32
proc ts_query_capture_count*(self: ptr TSQuery): uint32
proc ts_query_string_count*(self: ptr TSQuery): uint32
proc ts_query_capture_name_for_id*(self: ptr TSQuery, index: uint32,
                                   length: ptr uint32): cstring
proc ts_query_string_value_for_id*(self: ptr TSQuery, index: uint32,
                                    length: ptr uint32): cstring
proc ts_query_predicates_for_pattern*(self: ptr TSQuery, pattern_index: uint32,
                                       step_count: ptr uint32): ptr UncheckedArray[TSQueryPredicateStep]
proc ts_query_disable_capture*(self: ptr TSQuery, name: cstring, length: uint32)

proc ts_query_cursor_new*(): ptr TSQueryCursor
proc ts_query_cursor_delete*(self: ptr TSQueryCursor)
proc ts_query_cursor_exec*(self: ptr TSQueryCursor, query: ptr TSQuery, node: TSNode)
proc ts_query_cursor_next_match*(self: ptr TSQueryCursor, match: ptr TSQueryMatch): bool
proc ts_query_cursor_set_byte_range*(self: ptr TSQueryCursor,
                                      start_byte, end_byte: uint32): bool
proc ts_query_cursor_set_match_limit*(self: ptr TSQueryCursor, limit: uint32)

{.pop.}

proc free(p: pointer) {.importc, header: "<stdlib.h>", cdecl.}

proc sexp*(node: TSNode): string =
  ## Debug rendering of a subtree. Frees the C string.
  let s = ts_node_string(node)
  result = $s
  free(s)
